source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '10.0'

target 'TIanmu' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for TIanmu

  pod 'MJRefresh', '3.7.5'
  pod 'MJExtension' , '3.4.1'
  pod 'Masonry'  , '1.1.0'
  pod 'AFNetworking', '4.0.1'
  pod 'IQKeyboardManager', '6.5.11'
  pod 'SDWebImage', '5.15.5'
  pod 'MBProgressHUD', '1.2.0'
  pod 'YYWebImage', '1.0.4'
  pod 'SDCycleScrollView', '1.82'
end
